version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "minhasenha@forte"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "minhasenha@forte", "-Q", "select 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./src/Api
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
